apiVersion: v1
kind: ServiceAccount
metadata:
  name: costlens-backend-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "8aba5959-dcc3-44b5-a008-688cd50210c8"
  labels:
    azure.workload.identity/use: "true"
